# Image configuration
image:
  repository: abdosalah22/vois-explore-sre
  pullPolicy: IfNotPresent
  tag: "latest"

# Deployment configuration
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi