name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  lint:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
      if: github.ref == 'refs/heads/dev'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm ci

        - name: Run Jest tests
          run: npm run test

  snyk-scan:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk for dependencies and code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-build-and-push:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: [snyk-scan, lint, test]
    env:
      IMAGE: abdosalah22/vois-explore-sre
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive commit SHA tag
        id: vars
        run: |
          SHORT_SHA="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE:${SHORT_SHA} .

      - name: Trivy scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ env.SHORT_SHA }}

      - name: Push Docker image
        run: docker push $IMAGE:${SHORT_SHA}

  finish-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Finish Message
        run: echo "Post-merge pipeline finished successfully."