name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  ci-test:
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test

  snyk-scan:
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk for dependencies and code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-build-scan-push:
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '[skip ci]')
    runs-on: ubuntu-latest
    needs: [snyk-scan, lint, ci-test]
    env:
      IMAGE: abdosalah22/vois-explore-sre
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive commit SHA tag
        id: vars
        run: |
          SHORT_SHA="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE:${SHORT_SHA} .

      - name: Trivy scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ env.SHORT_SHA }}
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Push Docker image
        run: docker push $IMAGE:${SHORT_SHA}

  # Post-merge pipeline jobs
  cd-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run CD tests
        run: npm run test

  semantic-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [cd-test]
    env:
      IMAGE: abdosalah22/vois-explore-sre
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: release
        run: |
          npx semantic-release
          VERSION=$(git describe --tags --abbrev=0)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with version tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          docker build -t $IMAGE:${VERSION#v} -t $IMAGE:latest .
          docker push $IMAGE:${VERSION#v}
          docker push $IMAGE:latest

  helm-deploy-to-minikube:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [semantic-release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Deploy to Minikube
        run: |
          
          # Start Minikube cluster
          minikube start --driver=docker --memory=4096 --cpus=2
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
          kubectl config use-context minikube
          
          # Verify cluster is running
          kubectl cluster-info
          kubectl get nodes
          
          # Get version from semantic-release
          VERSION=${{ needs.semantic-release.outputs.version }}
          IMAGE_TAG=${VERSION#v}
          IMAGE=abdosalah22/vois-explore-sre
          
          # Verify Docker image exists
          if ! docker pull ${IMAGE}:${IMAGE_TAG}; then
            echo "Error: Docker image ${IMAGE}:${IMAGE_TAG} not found"
            exit 1
          fi

          # Load Docker image into Minikube
          echo "Loading image: ${IMAGE}:${IMAGE_TAG}"
          minikube image load ${IMAGE}:${IMAGE_TAG}

          # Verify image is loaded
          minikube image ls | grep vois-explore || echo "Image not found in minikube"
          
          # Use helm template + kubectl apply instead of helm install
          helm template vois-explore ./helm-chart \
            --set image.tag=${IMAGE_TAG} \
            --namespace default > deployment.yaml
          
          # Show what will be deployed
          echo "Generated Kubernetes manifests:"
          cat deployment.yaml
          kubectl apply -f deployment.yaml
          
          # Wait for deployment to be ready
          kubectl wait --for=condition=Available deployment/vois-explore --timeout=300s

          # Wait for deployment with better error handling
          if ! kubectl wait --for=condition=Available deployment/vois-explore --timeout=300s; then
            echo "Deployment failed. Debugging..."
            kubectl get pods -l app.kubernetes.io/name=vois-explore
            kubectl describe pods -l app.kubernetes.io/name=vois-explore
            kubectl get events --sort-by=.metadata.creationTimestamp
            exit 1
          fi
          
          # Verify deployment
          kubectl get pods -l app.kubernetes.io/name=vois-explore
          kubectl get services
          
          echo "Minikube deployment completed successfully!"

  finish-message:
    runs-on: ubuntu-latest
    needs: [helm-deploy-to-minikube]
    steps:
      - name: Finish Message
        run: echo "Post-merge pipeline finished successfully. Application deployed!"